### ISSUE TITLE
Release notes for deploy to app center from source code

### ISSUE THREAD

**Issue by danieeis** [builttoroam/pipeline_templates#36]
In some cases the release notes are found with the version control system, therefore, I think it is convenient to allow to parameterize the release notes from this source, since for now they must be in the artifact directory.

## Parameter
```
- name: appcenter_release_notes_source
  type: string
  default: 'artifact'
  values: 
  - artifact
  - source_control
```

## Variables
```
- name: release_notes_fullpath
${{ if eq(parameters.appcenter_release_notes_source, 'artifact') }}:
  value: '$(Pipeline.Workspace)/${{ parameters.artifact_name }}/${{ parameters.artifact_folder }}/${{ parameters.appcenter_release_notes_file }}'
${{ if eq(parameters.appcenter_release_notes_source, 'source_control') }}:
  value: '$(Build.SourcesDirectory)/${{ parameters.appcenter_release_notes_file }}'
```

I hope something like this can work 😅
